BoxLayoutExample:

<Options>:
    orientation: 'vertical'
    Button:
        text: "Profile"
    Button:
        text: "Setting"

<BoxlayoutExample>:
    #Force Method fo doing it
    orientation: 'vertical'
    Label:
        size_hint: None, None
        size: "100dp","100dp"
        text: ""
    Label:
        text: "Welcome to the game"
    Options:
        size_hint: None, None
        size: "50dp","50dp"
    
<MainWidget>:
    Label:
        text: "ahhah"